bcc-code/bcc-media-flows

activities/subtrans.go
services/subtrans/client.go

Start on https://github.com/bcc-code/bcc-media-flows/issues/43

Add fetching subs from subtrans

---

services/transcode/preview.go
services/vidispine/export.go
services/vidispine/vsapi/files_paths.go
utils/aux_path.go
utils/environment.go
workflows/asset_export-vx.go

Primariy used for local testing

feat: Allow different isilon prefixes

---

activities/transcode.go
bruno-collection/Transcribe File.bru
bruno-collection/bruno.json
bruno-collection/environments/Local.bru
bruno-collection/readme.md
cmd/httpin/main.go
cmd/worker/main.go
services/transcode/audio.go
workflows/transcribe-file.go
workflows/transcribe-vx.go

I have also added a Bruno collection. It's similar to Postman except it nicely stores the collection in a diffable/gitable format.

fix(transcribe): Transocde the files to wav first before attempting transcription

---

.vscode/launch.json
activities/vidispine/export.go
cmd/trigger_ui/css/style.css
cmd/trigger_ui/error.html
cmd/trigger_ui/index.html
cmd/trigger_ui/main.go
services/vidispine/export.go
workflows/export/vx_export.go

Trigger UI (version 1)

---

.gitignore
activities/vidispine/export.go
cmd/trigger_ui/index.html
cmd/trigger_ui/main.go
services/vidispine/export.go
services/vidispine/vsapi/metadata.go
services/vidispine/vsapi/xml_templates.go
workflows/export/vx_export.go

1. languages and audiosource makes changes to the metadata in mediabanken
2. the languages checkboxes will be active if the metadata from mediabanken matches
3. audio source dropdown will use data from mediabanken

save trigger states

---

services/vidispine/export.go

fix(export): Compare values not pointers

---

cmd/trigger_ui/main.go

This is just a QOL improvement for admins.

feat(ui): Add VX-ID to temproal custom string

---

activities/queues.go
activities/rclone.go
cmd/worker/main.go
paths/paths.go
services/rclone/upload.go
utils/wfutils/files.go
workflows/export/mux_files.go
workflows/export/prepare_files.go
workflows/export/vx_export_playout.go
workflows/export/vx_export_vod.go

Instead of waiting for all files to be ready, start upload of files when they are ready.

Move upload to right after files are ready.

---

cmd/trigger_ui/main.go

Just fetching the 1st title is not guaranteed that the result is the main clip title or that it is the same in all cases

fix(ui): Show correct title

---

activities/vidispine/export.go
cmd/trigger_ui/main.go
cmd/trigger_ui/templates/index.gohtml
services/vidispine/export.go
services/vidispine/service.go
services/vidispine/vsapi/subclip.go
workflows/export/vx_export.go

Allow exporting specific subclips without updating the subclip field in MB.

feat(export): define subclips to export

---

activities/files.go
services/ffmpeg/execute.go
utils/wfutils/files.go
workflows/export/vx_export.go
workflows/export/vx_export_vod.go

Uses 90% of the same flow as VOD, but with upload disabled, and destination folder being on isilon.
Just try to spot any issues that might occur with the existing flow.

feat(export): implement isilon destination

---

workflows/export/prepare_files.go
workflows/export/vx_export_vod.go

Improvement suggestion: Create a new activity so this + encoding step can be triggered as one future/audio pipeline.
This is basically a copy-pasta from BMM flow.

feature(export): Add audoio normalization to vod export

---

workflows/ingest/asset_ingest.go
workflows/ingest/masters.go

Pretty sure this is identical to the other masters, just needs some metadata. And if we add validation to the other masters, it should be added automatically here as well.
Most of the master imports are just reliant on metadata, which should be correctly set by the form regardless of the form.

feat(import): add orderform-podcast

---

activities/notifications.go
cmd/worker/main.go
go.mod
go.sum
services/notifications/client.go
services/notifications/send.go
services/notifications/targets.go
services/notifications/templates.go
services/notifications/templates/import_completed.gohtml
services/notifications/templates/simple_notification.gohtml
utils/workflows/notify.go
workflows/ingest/asset_ingest.go
workflows/ingest/common.go
workflows/ingest/masters.go
workflows/ingest/raw_material.go

Email bodies are yet to be completed properly, but this is the initial draft for import notifications.

feat(notifications): send emails on import complete

---

activities/preview.go
activities/rsync.go
activities/vidispine/files.go
cmd/httpin/main.go
cmd/worker/main.go
environment/environment.go
paths/paths.go
services/rsync/incremental.go
services/rsync/incremental_test.go
services/transcode/realtime.go
services/vidispine/service.go
services/vidispine/vsapi/files_paths.go
services/vidispine/vsapi/placeholder.go
workflows/ingest/incremental_ingest.go

Add support for incrementally ingesting a file.
Just need to point to a file, and the rest should be handled internally.
The live preview is handled internally by vidispine.

Incremental ingest

---

activities/audio.go
activities/transcode.go
activities/vidispine/meta.go
cmd/worker/main.go
go.mod
services/ffmpeg/probe.go
services/transcode/prepend-silence.go
services/vidispine/service.go
services/vidispine/vsapi/metadata.go
utils/tc_samples.go
utils/tc_samples_test.go
workflows/ingest/import_audio_from_reaper.go
workflows/ingest/incremental_ingest.go

feat: Import live recording

---

workflows/export/vx_export_bmm.go

To be used for sorting with BMM

feat(bmm-export): Add Recorded time to be sum of ImportedTime + ChapterStart

---

services/vidispine/vsapi/metadata_test.go
services/vidispine/vsapi/xml_templates.go

https://github.com/bcc-code/bcc-media-flows/issues/156

fix: Fields need to be inside the group

---

activities/files.go
cmd/worker/main.go
utils/files.go
utils/files_test.go
workflows/scheduled/files_cleanup.go

Added only for the `/mnt/temp` folder as a test

feat: Automatically cleanup temp files after 2 weeks

---

activities/analyze.go
activities/audio.go
activities/queues.go
cmd/trigger_ui/ingest-fix.go
cmd/trigger_ui/main.go
cmd/trigger_ui/templates/ingest-fix.gohtml
cmd/worker/main.go
services/ffmpeg/progress.go
services/transcode/audio.go
workflows/ingest/import_audio_from_reaper.go
workflows/ingest/mu1_mu2_extract.go

Missing:
* Actuall extract func
* Register activites
* Import files from main flow

Import audo form MU1 and MU2

---

activities/vidispine/files.go
services/vidispine/service.go
services/vidispine/vsapi/placeholder.go
workflows/ingest/raw_material.go

The width and the height seem to be the max sizes. I tries 180x180 and still got a 16:9 result. So I think this is a sane default.

Fix thumbnail generation

---

activities/audio.go
services/transcode/audio.go
workflows/vb_export/vb_export_abekas.go

This flow converts 5.1 to 4 mono streams discarding center and LFE channels

feat: Add support for exporting 5.1 to abeaks

---

workflows/ingest/import_audio_from_reaper.go
workflows/ingest/incremental_ingest.go

Only question here is if the different languages will ever have filename conflicts. If not, then this is easier to work with imo.

feat: send audio files from reaper to one path

---

activities/audio.go
activities/rclone.go
activities/vidispine/meta.go
cmd/worker/main.go
common/transcode.go
paths/paths.go
services/transcode/audio.go
services/vidispine/vscommon/fields.go
utils/workflows/files.go
workflows/vb_export/vb_export.go
workflows/vb_export/vb_export_dubbing.go

Tested as far as possible locally

Implemented export to dubbing.

---

cmd/trigger_ui/.env.example
services/cantemo/client.go
services/cantemo/client_test.go
services/cantemo/types.go

* Get transcription JSON
* Get Preview

Add Centemo API calls required by the BCCM Tools

---

services/transcode/multitrack.go
services/transcode/multitrack_test.go

The original only included the first 2 channels

Fix multitrack videpo generation

---

workflows/export/vx_export_bmm.go

Do not replace placeholder title with empty string

---

activities/bmm.go
activities/vidispine/client.go
activities/vidispine/meta.go
paths/paths.go
services/ffmpeg/ebur128_test.go
utils/workflows/encoding.go
utils/workflows/files.go
workflows/export/merge_export_data.go
workflows/export/mux_files.go
workflows/export/prepare_files.go
workflows/export/vx_export.go
workflows/export/vx_export_bmm.go
workflows/export/vx_export_vod.go
workflows/handle_multitrack.go
workflows/ingest/asset_ingest.go
workflows/ingest/common.go
workflows/ingest/import_audio_from_reaper.go
workflows/ingest/incremental_ingest.go
workflows/ingest/mu1_mu2_extract.go
workflows/normalize_audio.go
workflows/scheduled/files_cleanup.go
workflows/transcode_preview-file.go
workflows/transcribe-file.go
workflows/transcribe-vx.go
workflows/vb_export/vb_export.go
workflows/watch_folder_transcode.go
workflows/webhooks/bmm_simple_upload.go
workflows/webhooks/webhook.go

For more info see https://pkg.go.dev/go.temporal.io/sdk/contrib/tools/workflowcheck#section-readme

Make flows deterministic

---

utils/workflows/files.go
utils/workflows/time.go
utils/workflows/time_test.go

Effectively the change is only that I am sending in a pointer now.
```diff
- se.Get(date)
+ se.Get(&date)
```

Fixed issue + Added test

---

activities/cantemo/files.go
activities/cantemo/items.go
services/cantemo/client.go
services/cantemo/client_test.go
services/cantemo/types.go
workflows/ingest/asset_ingest_test.go
workflows/misc/cleanup_production.go
workflows/misc/cleanup_production_test.go

This is not "normal" day-to day operation, it's just a long running process (80k files) that needs to be completed as it prevents other things from working properly.
Note that it is tested locally and I'm mostly pushing it because I don't want to run the full thing on my laptop.

Added a function to cleanup a folder via Cantemo

---

activities/files.go
workflows/scheduled/files_cleanup.go

Do not delete reame files, add more folders to cleanup

---

activities/vidispine/items.go
activities/vidispine/meta.go
services/vidispine/service.go
services/vidispine/vsapi/items.go
services/vidispine/vsapi/search.go
services/vidispine/vsapi/search_test.go
workflows/scheduled/mediabanken_purge_trash.go
workflows/workflows.go

For some reason the internal job does not work and never has.

Add scheduled job for purging trash in mediabanken.

---

workflows/ingest/incremental_ingest.go
workflows/misc/transcribe-vx.go

Enable it for Incremental.
Solves #308

Add notifiction option to TranscribeVX

---

cmd/httpin/main.go
cmd/trigger_ui/main.go
common/transcode.go
services/transcode/h264.go
services/transcode/video.go
services/transcode/video_test.go
utils/resolution.go
utils/resolutions_test.go
workflows/export/mux_files_test.go
workflows/export/prepare_files.go
workflows/export/vx_export_vod.go

Also added tests for the new function as well as for the %2 issue.
What do you think about the `r.ResizeToFit(r2)` method? Suggestions for better names?
Maybe I should swap the `source` and `target`?

Fix the %2 issue on the other flow as well

---

cmd/fakerclone/main.go
services/rclone/jobs.go
services/rclone/ls.go

This is to simplify local testing

Add a quick and dirty fake rclone api

---

services/vidispine/export.go
workflows/export/merge_export_data.go
workflows/export/vx_export.go

* As of now untested
* Fallback is still NO, maybe we should pick some other language like "unknown" or "original" to differentiate between when we know that language it is and when we do not?

Fetch the language that is used for transcription and properly assign the language

---

workflows/misc/transcribe-vx.go

* No export processes use it
* It's not a "storage" (i.e. only used for preview inside MB)
* It's slow
* If it fails we should not fail the whole process

Do not wait for sidecar import

---

utils/workflows/common.go
workflows/ingest/asset_ingest.go

Also make the "Distribution" form not be an error

Update retry defaults so we fail faster

---

workflows/ingest/asset_ingest.go
workflows/ingest/masters.go

The basic idea is to re-use the master import but run it for each file (minus renaming the file).
This is currently not testable locally without a big refactor of several services that I started on but will not be able to complete to any sane extent before the end of the sprint so it will have to endure a production test.

VB bulk import

---

activities/vidispine/export.go
cmd/trigger_ui/main.go
cmd/trigger_ui/templates/vx-export.gohtml
language_config.go
services/vidispine/export.go
workflows/export/vx_export.go
workflows/export/vx_export_vod.go

Note: I also added a checkbox to the UI that is on by default.

feat(vod): Add support for exporting AI-Generated Subtitles

---

common/transcode.go
services/ffmpeg/probe.go
services/transcode/audio.go
services/transcode/audio_test.go
workflows/export/vx_export_bmm.go

Implement CBR for MP3

---

workflows/vb_export/vb_export_abekas.go

Added check for audio only files when exporting to abekas
if audio only file is detected new `VBExportToAbekasAudioOnly` function get run to handle that case

add audio-only export to Abekas check and function to handle the export
